repos:
  - repo: local
    hooks:
      - id: mojo-format
        name: mojo-format
        entry: magic run format
        language: system
        files: '\.(mojo|🔥)$'
        stages: [commit]
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.40.0
  #   hooks:
  #   - id: markdownlint
  #     args: ['--config', 'stdlib/scripts/.markdownlint.yaml', '--fix']
