[project]
authors = ["Brian Grenier <grenierb96@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "A json library for Mojo"
name = "emberjson"
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]
version = "0.1.6"
license = "MIT"
license-file = "LICENSE"
homepage = "https://github.com/bgreni/EmberJson"
repository = "https://github.com/bgreni/EmberJson"

[tasks]
build = { cmd = "magic run rattler-build build --recipe recipes -c https://conda.modular.com/max-nightly -c conda-forge --skip-existing=all", env = {MODULAR_MOJO_IMPORT_PATH = "$CONDA_PREFIX/lib/mojo"}, depends-on=["template"] }
template = { cmd = "magic run python3 scripts/templater.py" }
format = { cmd = "magic run mojo format -l 80 emberjson test bench.mojo fuzz.mojo" }
test = { cmd = "magic run clean ; magic run mojo test" }
bench = { cmd = "magic run mojo build bench.mojo && ./bench && rm bench" }
clean = { cmd = "rm -r output &> /dev/null" }
update_and_build = { cmd = "magic update && magic run test && magic run build" }
publish = { cmd = "./scripts/publish.sh", env = { PREFIX_API_KEY = "$PREFIX_API_KEY" }}
precommit = { depends-on = ["format", "test"] }
update_and_test = "magic update && magic run test && magic run bench"

[dependencies]
max = ">=25.4.0.dev2025050605,<26"



[feature.fuzz.tasks]
fuzz = "magic run mojo -D ASSERT=all fuzz.mojo"

[feature.fuzz.dependencies]
faker = ">=36.1.1,<37"

[environments]
fuzz = { features = ["fuzz"], solve-group = "default" }
