name: Branch workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml
  
  package:
    uses: ./.github/workflows/package.yml
  
  lint:
    uses: ./.github/workflows/test_pre_commit.yml