name: Run the testing suite

on:
    workflow_call:

jobs:
    test:
        timeout-minutes: 30
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run the test suite  
              run: |
                curl -fsSL https://pixi.sh/install.sh | sh
                export PATH="$HOME/.pixi/bin:$PATH"
                pixi run test