

name: Run pre-commit
on:
  workflow_call:

jobs:
  lint:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30

    defaults:
      run:
        shell: bash
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4      
      - name: Run pre-commit
        run: |
          curl -fsSL https://pixi.sh/install.sh | sh
          export PATH="$HOME/.pixi/bin:$PATH"
          pip install pre-commit
          pre-commit install
          pixi run pre-commit run --all-files

